# Generated by Django 3.0.4 on 2020-04-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_populate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'default_related_name': 'contract', 'ordering': ('number', 'contractor'), 'verbose_name': 'contract'},
        ),
        migrations.AlterModelOptions(
            name='contractarticle',
            options={'default_related_name': 'contract_articles', 'ordering': ('contract',), 'verbose_name': 'contract articles'},
        ),
        migrations.AlterModelOptions(
            name='taskarticles',
            options={'default_related_name': 'task_articles', 'ordering': ('task',), 'verbose_name': 'task articles'},
        ),
        migrations.AlterField(
            model_name='contractarticle',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_articles', to='budget.Contract'),
        ),
        migrations.AlterField(
            model_name='contractarticle',
            name='contract_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_articles', to='budget.Articles'),
        ),
        migrations.AlterField(
            model_name='taskarticles',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_articles', to='budget.Articles'),
        ),
        migrations.AlterField(
            model_name='taskarticles',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_articles', to='budget.Task'),
        ),
    ]
