# Generated by Django 3.0.4 on 2020-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20200319_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocument',
            name='payment_date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='payment_date2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
