# Generated by Django 3.0.4 on 2020-04-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20200401_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractArticles',
            new_name='ContractArticle',
        ),
        migrations.RenameModel(
            old_name='FinDocumentArticles',
            new_name='FinDocumentArticle',
        ),
    ]
