# Generated by Django 3.0.4 on 2020-04-12 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20200402_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='contractarticle',
            name='contract_article',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_articles', to='budget.Articles'),
        ),
        migrations.AlterField(
            model_name='task',
            name='article',
            field=models.ManyToManyField(through='budget.TaskArticles', to='budget.Articles'),
        ),
    ]
