# Generated by Django 3.0.4 on 2020-04-22 20:12

import autoslug.fields
from django.db import migrations
from budget.models import Task
def migrate_data_forward(apps, schema_editor):
    for instance in Task.objects.all():
        print("Generating slug for %s"%instance)
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20200412_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractarticle',
            options={'default_related_name': 'contract_articles', 'ordering': ('contract',), 'verbose_name': 'contract_articles'},
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
