# Generated by Django 3.0.4 on 2020-04-23 18:35

from django.db import migrations, models
from budget.models import Contractor
def migrate_data_forward(apps, schema_editor):
    for instance in Contractor.objects.all():
        print("Generating slug for %s"%instance)
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20200422_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='slug_name',
            field=models.SlugField(default=None, max_length=200, null=True, unique=True),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
