# Generated by Django 3.0.4 on 2020-04-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_contractor_slug_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='slug_name',
            new_name='slug',
        ),
    ]
