# Generated by Django 3.0.4 on 2020-04-25 20:37

from django.db import migrations, models
from budget.models import FinancialDocument

def migrate_data_forward(apps, schema_editor):
    for instance in FinancialDocument.objects.all():
        print("Generating slug for %s"%instance)
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_contract_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocument',
            name='slug',
            field=models.SlugField(default=None, max_length=200, null=True, unique=True),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
